Enhancements for experiment component tree including queue, console and add new run engine controls
cnpem/sophys-web pull request #20
Opened 2024-11-22 20:01 UTC by brnovasco

2024-11-23 13:41 UTC, matyson requested changes
the rest looks fine

2024-11-23 13:41 UTC, matyson commented on apps/spu-ui/src/app/_components/console.tsx
should think a better unique way, maybe

2024-11-25 12:22 UTC, brnovasco commented on apps/spu-ui/src/app/_components/console.tsx
I agree this doesn't fix the issue. It is just adding another part of the message in the combination hoping it would be unique this time. 
But I'm not sure where we can find a true uniqueness from the original stream. Do you have any idea on how to do this?

2024-11-25 13:15 UTC, matyson commented on apps/spu-ui/src/app/_components/console.tsx
maybe modify the server route to generate a unique id and pass it through the response object ?

2024-11-25 16:05 UTC, matyson approved these changes
nice

2024-11-25 16:05 UTC, merged